/**
 * Base seed — idempotent. Safe to re-run against the shared database (ADR-027): it upserts
 * reference/config data and only inserts employees that do not exist yet. It never deletes
 * business data (orders, invoices). Rolling demo orders are generated by the API (Phase 9).
 */
import { randomBytes } from 'node:crypto';
import { existsSync } from 'node:fs';
import { hash } from '@node-rs/argon2';
import { PrismaPg } from '@prisma/adapter-pg';
import { applyMultiplierBps } from '@fernleaf/domain';
import { ALL_PERMISSIONS, type DashboardKind, type Permission } from '@fernleaf/shared';
import { PrismaClient } from '../src/generated/prisma/client';
import {
  ALLERGENS,
  CATEGORIES,
  DIETARY_TAGS,
  DISHES,
  ENTERPRISE_OVERRIDES,
  OPTIONS,
  PACKAGING_TYPES,
  PORTION_SIZES,
  STARTUP_MISSING_DISHES,
  STARTUP_MISSING_OPTIONS,
  STATIONS,
} from './seed/catalogue-data';
import { COMPANIES, generateEmployees, KITCHEN_HOLIDAYS, PUBLIC_EMAIL_DOMAINS } from './seed/companies-data';

if (existsSync('.env')) process.loadEnvFile('.env');

const databaseUrl = process.env.DIRECT_URL ?? process.env.DATABASE_URL;
if (!databaseUrl) throw new Error('DATABASE_URL (or DIRECT_URL) is required to seed');
const prisma = new PrismaClient({ adapter: new PrismaPg({ connectionString: databaseUrl }) });

type IdMap = Map<string, string>;

// ───────────────────────── Roles & staff ─────────────────────────

interface RoleSeed {
  key: string;
  name: string;
  description: string;
  dashboard: DashboardKind;
  permissions: Permission[];
}

// Role → permission mapping from docs/TRD.md §4.8. Admin gets everything except driving.
const ROLES: RoleSeed[] = [
  {
    key: 'ADMIN',
    name: 'Admin',
    description: 'Runs the platform: catalogue, pricing, companies, orders, billing, settings. Can override anything.',
    dashboard: 'ADMIN',
    permissions: ALL_PERMISSIONS.filter((p) => p !== 'deliveries.own'),
  },
  {
    key: 'KITCHEN',
    name: 'Kitchen',
    description: 'Cooks prep units and marks them started/done. Read-only on what the kitchen needs.',
    dashboard: 'KITCHEN',
    permissions: ['dashboard.view', 'kitchen.read', 'kitchen.work', 'orders.read', 'catalogue.read', 'menu.read', 'reference.read'],
  },
  {
    key: 'DISPATCH',
    name: 'Dispatch',
    description: 'Moves cooked orders out of the door, assigns drivers, tracks deliveries.',
    dashboard: 'DISPATCH',
    permissions: ['dashboard.view', 'dispatch.read', 'dispatch.manage', 'kitchen.read', 'orders.read', 'companies.read'],
  },
  {
    key: 'DRIVER',
    name: 'Driver',
    description: 'Sees only their own drops for today and marks them delivered.',
    dashboard: 'DRIVER',
    permissions: ['dashboard.view', 'deliveries.own'],
  },
];

const REVIEW_PASSWORD = 'Test@1234';

const STAFF: { email: string; name: string; roleKey: string; password?: string; phone?: string }[] = [
  { email: 'admin@test.com', name: 'Aditi Rao', roleKey: 'ADMIN', password: REVIEW_PASSWORD },
  { email: 'kitchen@test.com', name: 'Kiran Shetty', roleKey: 'KITCHEN', password: REVIEW_PASSWORD },
  { email: 'dispatch@test.com', name: 'Deepak Verma', roleKey: 'DISPATCH', password: REVIEW_PASSWORD },
  { email: 'driver@test.com', name: 'Dev Malhotra', roleKey: 'DRIVER', password: REVIEW_PASSWORD, phone: '+91 98480 11001' },
  { email: 'ravi.kumar@fernleaf.kitchen', name: 'Ravi Kumar', roleKey: 'DRIVER', phone: '+91 98480 11002' },
  { email: 'sana.shaikh@fernleaf.kitchen', name: 'Sana Shaikh', roleKey: 'DRIVER', phone: '+91 98480 11003' },
  { email: 'priya.nair@fernleaf.kitchen', name: 'Priya Nair', roleKey: 'KITCHEN' },
];

async function seedAccess(): Promise<IdMap> {
  const roleIds: IdMap = new Map();
  for (const role of ROLES) {
    const row = await prisma.role.upsert({
      where: { key: role.key },
      update: { name: role.name, description: role.description, dashboard: role.dashboard, permissions: role.permissions, isSystem: true },
      create: { ...role, isSystem: true },
    });
    roleIds.set(role.key, row.id);
  }

  const staffIds: IdMap = new Map();
  for (const staff of STAFF) {
    const roleId = roleIds.get(staff.roleKey)!;
    // Review accounts always get their exact password back; other staff get a random, never-published
    // password on creation and keep whatever they have afterwards.
    const passwordHash = await hash(staff.password ?? randomBytes(18).toString('base64url'));
    const row = await prisma.staffUser.upsert({
      where: { email: staff.email },
      update: { name: staff.name, roleId, isActive: true, phone: staff.phone ?? null, ...(staff.password ? { passwordHash } : {}) },
      create: { email: staff.email, name: staff.name, roleId, phone: staff.phone ?? null, passwordHash },
    });
    staffIds.set(staff.email, row.id);
  }
  return staffIds;
}

// ───────────────────────── Reference data ─────────────────────────

async function seedReference() {
  const upsertList = async (
    names: readonly string[],
    upsert: (name: string, sortOrder: number) => Promise<{ id: string }>,
  ): Promise<IdMap> => {
    const ids: IdMap = new Map();
    for (const [i, name] of names.entries()) ids.set(name, (await upsert(name, i)).id);
    return ids;
  };
  const args = (name: string, sortOrder: number) => ({ where: { name }, update: { sortOrder }, create: { name, sortOrder } });

  const allergens = await upsertList(ALLERGENS, (n, i) => prisma.allergen.upsert(args(n, i)));
  const tags = await upsertList(DIETARY_TAGS, (n, i) => prisma.dietaryTag.upsert(args(n, i)));
  const stations = await upsertList(STATIONS, (n, i) => prisma.kitchenStation.upsert(args(n, i)));
  const sizes = await upsertList(PORTION_SIZES, (n, i) => prisma.portionSize.upsert(args(n, i)));
  const packaging: IdMap = new Map();
  for (const [i, p] of PACKAGING_TYPES.entries()) {
    const row = await prisma.packagingType.upsert({
      where: { name: p.name },
      update: { description: p.description, sortOrder: i },
      create: { name: p.name, description: p.description, sortOrder: i },
    });
    packaging.set(p.name, row.id);
  }
  return { allergens, tags, stations, sizes, packaging };
}

type Ref = Awaited<ReturnType<typeof seedReference>>;

// ───────────────────────── Catalogue ─────────────────────────

async function seedCatalogue(ref: Ref) {
  const optionIds: IdMap = new Map();
  for (const o of OPTIONS) {
    const row = await prisma.option.upsert({
      where: { name: o.name },
      update: { costCents: o.costCents, isActive: true },
      create: { name: o.name, costCents: o.costCents },
    });
    optionIds.set(o.name, row.id);
    await prisma.optionAllergen.deleteMany({ where: { optionId: row.id } });
    await prisma.optionDietaryTag.deleteMany({ where: { optionId: row.id } });
    await prisma.optionAllergen.createMany({ data: o.allergens.map((a) => ({ optionId: row.id, allergenId: ref.allergens.get(a)! })) });
    await prisma.optionDietaryTag.createMany({ data: o.tags.map((t) => ({ optionId: row.id, dietaryTagId: ref.tags.get(t)! })) });
    if (o.portions) {
      for (const [size, extraCents] of Object.entries(o.portions)) {
        const portionSizeId = ref.sizes.get(size)!;
        await prisma.optionPortion.upsert({
          where: { optionId_portionSizeId: { optionId: row.id, portionSizeId } },
          update: { extraCents },
          create: { optionId: row.id, portionSizeId, extraCents },
        });
      }
    }
  }

  const dishIds: IdMap = new Map();
  for (const d of DISHES) {
    const data = {
      name: d.name,
      description: d.description,
      temperature: d.temperature,
      costCents: d.costCents,
      stationId: d.station ? ref.stations.get(d.station)! : null,
      minOrderQty: d.minOrderQty ?? null,
      isActive: true,
    };
    const dish = await prisma.dish.upsert({ where: { sku: d.sku }, update: data, create: { sku: d.sku, ...data } });
    dishIds.set(d.sku, dish.id);
    await prisma.dishAllergen.deleteMany({ where: { dishId: dish.id } });
    await prisma.dishDietaryTag.deleteMany({ where: { dishId: dish.id } });
    await prisma.dishAllergen.createMany({ data: d.allergens.map((a) => ({ dishId: dish.id, allergenId: ref.allergens.get(a)! })) });
    await prisma.dishDietaryTag.createMany({ data: d.tags.map((t) => ({ dishId: dish.id, dietaryTagId: ref.tags.get(t)! })) });

    for (const [gi, g] of d.groups.entries()) {
      const group = await prisma.optionGroup.upsert({
        where: { dishId_name: { dishId: dish.id, name: g.name } },
        update: { isRequired: g.isRequired, maxSelections: g.maxSelections ?? 1, sortOrder: gi + 1, usesPortions: g.usesPortions ?? false },
        create: { dishId: dish.id, name: g.name, isRequired: g.isRequired, maxSelections: g.maxSelections ?? 1, sortOrder: gi + 1, usesPortions: g.usesPortions ?? false },
      });
      await prisma.optionGroupItem.deleteMany({ where: { groupId: group.id } });
      await prisma.optionGroupItem.createMany({
        data: g.options.map((name, oi) => ({ groupId: group.id, optionId: optionIds.get(name)!, sortOrder: oi + 1 })),
      });
      await prisma.optionGroupPortionSize.deleteMany({ where: { groupId: group.id } });
      if (g.usesPortions) {
        await prisma.optionGroupPortionSize.createMany({
          data: PORTION_SIZES.map((s, si) => ({ groupId: group.id, portionSizeId: ref.sizes.get(s)!, sortOrder: si + 1 })),
        });
      }
    }
  }
  return { optionIds, dishIds };
}

type Catalogue = Awaited<ReturnType<typeof seedCatalogue>>;

// ───────────────────────── Pricing ─────────────────────────

async function seedPricing(cat: Catalogue): Promise<IdMap> {
  const tierIds: IdMap = new Map();
  const tier = async (name: string, data: { description: string; derivation: 'MANUAL' | 'FROM_COST' | 'FROM_TIER'; baseTierId?: string | null; multiplierBps?: number | null }) => {
    const row = await prisma.priceTier.upsert({
      where: { name },
      update: { ...data, baseTierId: data.baseTierId ?? null, multiplierBps: data.multiplierBps ?? null },
      create: { name, ...data, baseTierId: data.baseTierId ?? null, multiplierBps: data.multiplierBps ?? null },
    });
    tierIds.set(name, row.id);
    return row.id;
  };

  const standard = await tier('Standard', { description: 'List prices, typed in. The default tier.', derivation: 'MANUAL' });
  const enterprise = await tier('Enterprise', { description: 'Standard − 10%, with a few negotiated overrides.', derivation: 'FROM_TIER', baseTierId: standard, multiplierBps: 9_000 });
  await tier('Partner', { description: 'Cost × 2.4 for partner hospitals.', derivation: 'FROM_COST', multiplierBps: 24_000 });
  const startup = await tier('Startup', { description: 'Hand-priced list for small firms; not every dish is offered.', derivation: 'MANUAL' });

  const setDish = (tierId: string, dishId: string, priceCents: number) =>
    prisma.dishPrice.upsert({ where: { tierId_dishId: { tierId, dishId } }, update: { priceCents }, create: { tierId, dishId, priceCents } });
  const setOption = (tierId: string, optionId: string, priceCents: number) =>
    prisma.optionPrice.upsert({ where: { tierId_optionId: { tierId, optionId } }, update: { priceCents }, create: { tierId, optionId, priceCents } });

  for (const d of DISHES) {
    const dishId = cat.dishIds.get(d.sku)!;
    await setDish(standard, dishId, d.priceCents);
    if (STARTUP_MISSING_DISHES.includes(d.sku)) {
      await prisma.dishPrice.deleteMany({ where: { tierId: startup, dishId } });
    } else {
      await setDish(startup, dishId, applyMultiplierBps(d.priceCents, 9_500));
    }
    const override = ENTERPRISE_OVERRIDES[d.sku];
    if (override !== undefined) await setDish(enterprise, dishId, override);
  }
  for (const o of OPTIONS) {
    const optionId = cat.optionIds.get(o.name)!;
    await setOption(standard, optionId, o.priceCents);
    if (STARTUP_MISSING_OPTIONS.includes(o.name)) {
      await prisma.optionPrice.deleteMany({ where: { tierId: startup, optionId } });
    } else {
      await setOption(startup, optionId, o.priceCents);
    }
  }
  return tierIds;
}

// ───────────────────────── Menu ─────────────────────────

async function seedMenu(cat: Catalogue) {
  const categoryIds: IdMap = new Map();
  const menuItemIdsBySku: IdMap = new Map();
  for (const [ci, c] of CATEGORIES.entries()) {
    const row = await prisma.menuCategory.upsert({
      where: { slug: c.slug },
      update: { name: c.name, description: c.description, sortOrder: ci + 1, isSecret: c.isSecret ?? false, isActive: true },
      create: { slug: c.slug, name: c.name, description: c.description, sortOrder: ci + 1, isSecret: c.isSecret ?? false },
    });
    categoryIds.set(c.slug, row.id);
    const dishes = DISHES.filter((d) => d.category === c.slug);
    for (const [di, d] of dishes.entries()) {
      const dishId = cat.dishIds.get(d.sku)!;
      const item = await prisma.menuItem.upsert({
        where: { categoryId_dishId: { categoryId: row.id, dishId } },
        update: { sortOrder: di + 1, isActive: true },
        create: { categoryId: row.id, dishId, sortOrder: di + 1 },
      });
      menuItemIdsBySku.set(d.sku, item.id);
    }
  }
  return { categoryIds, menuItemIdsBySku };
}

// ───────────────────────── Settings ─────────────────────────

async function seedSettings(tierIds: IdMap) {
  const settings = {
    kitchenWorkingDays: [1, 2, 3, 4, 5, 6, 7], // the live kitchen cooks every day (A-03)
    cutoffTime: 16 * 60,
    cutoffDaysBefore: 2,
    kitchenBufferMinutes: 30,
    atRiskMinutes: 30,
    onTimeGraceMinutes: 0,
    deliveryWindowStart: 7 * 60,
    deliveryWindowEnd: 21 * 60,
    defaultPriceTierId: tierIds.get('Standard')!,
    publicEmailDomains: PUBLIC_EMAIL_DOMAINS,
  };
  // Only create: re-seeding must not overwrite settings an admin changed in the UI.
  await prisma.platformSettings.upsert({ where: { id: 1 }, update: {}, create: { id: 1, ...settings } });
  for (const h of KITCHEN_HOLIDAYS) {
    await prisma.kitchenHoliday.upsert({ where: { date: new Date(`${h.date}T00:00:00Z`) }, update: { name: h.name }, create: { date: new Date(`${h.date}T00:00:00Z`), name: h.name } });
  }
}

// ───────────────────────── Companies & employees ─────────────────────────

async function seedCompanies(ref: Ref, tierIds: IdMap, menu: Awaited<ReturnType<typeof seedMenu>>, staffIds: IdMap) {
  let employeesCreated = 0;
  for (const c of COMPANIES) {
    const base = {
      priceTierId: c.tier ? tierIds.get(c.tier)! : null,
      billingContactName: c.billing.name,
      billingEmail: c.billing.email,
      billingPhone: c.billing.phone,
      billingAddress: c.billing.address,
      workingDays: c.workingDays,
      defaultDeliveryTime: c.defaultDeliveryTime,
      dispatchLeadMinutes: c.dispatchLeadMinutes,
      defaultPackagingTypeId: ref.packaging.get(c.packaging)!,
      driverInstructions: c.driverInstructions,
      defaultDriverId: staffIds.get(c.defaultDriverEmail) ?? null,
    };
    const company = await prisma.company.upsert({ where: { name: c.name }, update: base, create: { name: c.name, ...base } });

    await prisma.companyDomain.upsert({ where: { domain: c.domain }, update: { companyId: company.id }, create: { companyId: company.id, domain: c.domain } });

    let defaultAddressId: string | null = null;
    for (const a of c.addresses) {
      const data = { line1: a.line1, line2: a.line2 ?? null, city: a.city, state: a.state, postalCode: a.postalCode, deliveryNotes: a.deliveryNotes ?? '', isActive: true };
      const existing = await prisma.companyAddress.findFirst({ where: { companyId: company.id, label: a.label } });
      const address = existing
        ? await prisma.companyAddress.update({ where: { id: existing.id }, data })
        : await prisma.companyAddress.create({ data: { companyId: company.id, label: a.label, ...data } });
      defaultAddressId ??= address.id;
    }

    for (const h of c.holidays) {
      const date = new Date(`${h.date}T00:00:00Z`);
      await prisma.companyHoliday.upsert({ where: { companyId_date: { companyId: company.id, date } }, update: { name: h.name }, create: { companyId: company.id, date, name: h.name } });
    }

    for (const slug of c.hiddenCategorySlugs) {
      const categoryId = menu.categoryIds.get(slug)!;
      await prisma.companyHiddenCategory.upsert({
        where: { companyId_categoryId: { companyId: company.id, categoryId } },
        update: {},
        create: { companyId: company.id, categoryId },
      });
    }
    for (const sku of c.hiddenDishSkus) {
      const menuItemId = menu.menuItemIdsBySku.get(sku)!;
      await prisma.companyHiddenMenuItem.upsert({
        where: { companyId_menuItemId: { companyId: company.id, menuItemId } },
        update: {},
        create: { companyId: company.id, menuItemId },
      });
    }

    // Employees: insert the ones that don't exist yet (bulk, so re-runs are cheap).
    const employees = generateEmployees(c, ALLERGENS, ['Vegetarian', 'Vegan', 'Jain', 'Gluten-free']);
    const created = await prisma.employee.createMany({
      data: employees.map((e) => ({
        companyId: company.id,
        name: e.name,
        email: e.email,
        phone: e.phone,
        canChooseAddress: e.canChooseAddress,
        canChangeDeliveryTime: e.canChangeDeliveryTime,
        canChangePackaging: e.canChangePackaging,
      })),
      skipDuplicates: true,
    });
    employeesCreated += created.count;
    const rows = await prisma.employee.findMany({ where: { email: { in: employees.map((e) => e.email) } }, select: { id: true, email: true } });
    const idByEmail = new Map(rows.map((r) => [r.email, r.id]));
    await prisma.employeeAllergen.createMany({
      data: employees.flatMap((e) => e.allergens.map((a) => ({ employeeId: idByEmail.get(e.email)!, allergenId: ref.allergens.get(a)! }))),
      skipDuplicates: true,
    });
    await prisma.employeeDietaryPreference.createMany({
      data: employees.flatMap((e) => e.diets.map((t) => ({ employeeId: idByEmail.get(e.email)!, dietaryTagId: ref.tags.get(t)! }))),
      skipDuplicates: true,
    });

    // Owner = first generated employee (A-38); default address = first address.
    await prisma.company.update({
      where: { id: company.id },
      data: { ownerEmployeeId: idByEmail.get(employees[0]!.email)!, defaultAddressId },
    });
  }
  return employeesCreated;
}

async function main(): Promise<void> {
  const started = Date.now();
  const staffIds = await seedAccess();
  const ref = await seedReference();
  const cat = await seedCatalogue(ref);
  const tierIds = await seedPricing(cat);
  const menu = await seedMenu(cat);
  await seedSettings(tierIds);
  const employeesCreated = await seedCompanies(ref, tierIds, menu, staffIds);
  console.log(
    `Seeded: ${ROLES.length} roles, ${STAFF.length} staff, ${OPTIONS.length} options, ${DISHES.length} dishes, ` +
      `${tierIds.size} tiers, ${CATEGORIES.length} categories, ${COMPANIES.length} companies ` +
      `(${employeesCreated} new employees) in ${Math.round((Date.now() - started) / 1000)}s.`,
  );
}

main()
  .catch((err: unknown) => {
    console.error(err);
    process.exitCode = 1;
  })
  .finally(() => prisma.$disconnect());
